#!/usr/bin/env ruby

require "pathname"
$:.unshift(Pathname(__dir__) + ".." + "lib")

require "weatherbot"

period = ARGV[0]

selected_hours = case period
                 when "lunchtime"
                   [12, 13, 14]
                 when "hometime"
                   [17, 18, 19]
                 when /\A(([0-9]+,?)+)\z/
                   period.split(",").map(&:to_i)
                 else
                   [12, 13, 14, 17, 18, 19]
                 end

begin
  api = Weatherbot::API.new(api_key: ENV.fetch("WUNDERGROUND_API_KEY"))
  forecast = Weatherbot::Forecast.new(api: api, region: "UK", city: "London")
rescue WeatherbotException => e
  abort "Couldn't fetch weather forecast: #{e.message}"
end

snow = false

forecast.hours.select { |h| selected_hours.include?(h.hour) }.each do |hour|
  snow = true if hour.snow?

  print "#{hour.hour}:00: "
  print "#{hour.temperature}ºC (feels like #{hour.feels_like}ºC). "

  if hour.temperature > 25
    print "Absolutely roasting! "
  elsif hour.temperature > 20
    print "Pretty hot. "
  end

  if hour.dew_point > 22
    print "Unbearably humid. "
  elsif hour.dew_point > 18
    print "Uncomfortably humid. "
  elsif hour.dew_point > 16
    print "Pretty humid. "
  end

  if hour.cloud_cover > 90
    print "Really cloudy. "
  elsif hour.cloud_cover > 50
    print "Cloudy. "
  elsif hour.cloud_cover < 5
    print "Not a cloud in the sky. "
  end

  if hour.chance_of_rain > 80
    print "Basically guaranteed to rain. "
  elsif hour.chance_of_rain > 40
    print "Rain is likely. "
  elsif hour.chance_of_rain > 0
    print "Rain is possible but unlikely. "
  end

  if hour.wind_speed > 50
    print "Literally gale-force winds. Be careful! "
  elsif hour.wind_speed > 35
    print "Very windy. "
  elsif hour.wind_speed > 20
    print "Pretty windy. "
  elsif hour.wind_speed > 10
    print "Breezy. "
  end

  puts
end

if snow
  puts "IT'S GOING TO SNOW!!!!!!!"
end
